-- 코드를 입력하세요
-- SELECT * FROM CAR_RENTAL_COMPANY_CAR;
-- SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY;
-- SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN;

SELECT A.CAR_ID, A.CAR_TYPE, (30*A.DAILY_FEE*(1-B.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE B.DURATION_TYPE='30일 이상'
AND (A.CAR_TYPE ='세단' OR A.CAR_TYPE = 'SUV')
AND A.CAR_ID NOT IN (
                     SELECT CAR_ID 
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                     WHERE TO_CHAR(START_DATE,'YYYYMMDD') <= '20221130'
                     AND
                     TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221101'
                    )
AND (30*A.DAILY_FEE*(1-B.DISCOUNT_RATE/100)) BETWEEN 500000 AND 1999999
ORDER BY 3 DESC, 2, 1 DESC;
