
SELECT FLAVOR 
FROM( SELECT A.FLAVOR, A.TOTAL_ORDER, B.INGREDIENT_TYPE 
      FROM FIRST_HALF A, ICECREAM_INFO B 
      WHERE A.FLAVOR = B.FLAVOR AND A.TOTAL_ORDER > 3000 AND B.INGREDIENT_TYPE='fruit_based'
      ORDER BY A.TOTAL_ORDER DESC);
