SELECT A.MEMBER_NAME, B.REVIEW_TEXT, TO_CHAR(B.REVIEW_DATE, 'YYYY-MM-DD')
FROM MEMBER_PROFILE A,
     REST_REVIEW B, 
    (SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) =
    (SELECT MAX(COUNT(*)) 
    FROM REST_REVIEW
    GROUP BY MEMBER_ID)) C
WHERE A.MEMBER_ID = B.MEMBER_ID
AND
B.MEMBER_ID = C.MEMBER_ID
ORDER BY 3, 2;