SELECT INFO.REST_ID
     , INFO.REST_NAME
     , INFO.FOOD_TYPE
     , INFO.FAVORITES
     , INFO.ADDRESS
     , ROUND(AVG(REVIEW.REVIEW_SCORE), 2) AS SCORE
  FROM REST_INFO INFO
     , REST_REVIEW REVIEW
 WHERE INFO.REST_ID = REVIEW.REST_ID
   AND INFO.ADDRESS LIKE '서울%'
   --AND REVIEW.REVIEW_SCORE IS NOT NULL
 GROUP BY INFO.REST_ID
     , INFO.REST_NAME
     , INFO.FOOD_TYPE
     , INFO.FAVORITES
     , INFO.ADDRESS
 ORDER BY 6 DESC, 4 DESC